# TODO: Add `SQLALCHEMY_DATABASE_URI` as an environmental variable.
---
matrix:
  include:
    - language: python
      python: 3.7
      services:
        - docker
      before_script:
        - "cd heartbeat"
      script:
        - "pip install -r requirements.txt"
        - nosetests
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t digitamo/heartbeat .
        - docker push digitamo/heartbeat
    - language: python
      python: 3.7
      services:
        - docker
      before_script:
        - "cd search"
      script:
        - "pip install -r requirements.txt"
        - nosetests
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t digitamo/heartbeat .
        - docker push digitamo/heartbeat
