---
matrix:
  include:
    - before_script:
        - "cd heartbeat"
      language: python
      python: 3.7.1
      script:
        - "pip install -r requirements.txt"
        - nosetests
    - before_script:
        - "cd search"
      language: python
      python: 3.7.1
      script:
        - "pip install -r requirements.txt"
        - nosetests
