"""empty message

Revision ID: 55e0e4f80758
Revises: 
Create Date: 2019-07-23 20:18:17.303527

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '55e0e4f80758'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_source',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sequence_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
                    sa.Column('position', sa.BigInteger(), nullable=False),
                    sa.Column('topic', sa.String(length=255), nullable=False),
                    sa.Column('state', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('index', 'event_source', ['sequence_id', 'position'], unique=True)
    op.create_table('vehicle',
                    sa.Column('id', sa.String(length=17), nullable=False),
                    sa.Column('reg_no', sa.String(length=6), nullable=True),
                    sa.Column('customer_id', sa.Integer(), nullable=True),
                    sa.Column('heartbeat_ts', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_index('index', table_name='event_source')
    op.drop_table('event_source')
    # ### end Alembic commands ###
